packages:
  - 'packages/*'
packageExtensions:
  recast@0.23.11:
    dependencies:
      '@babel/parser': '7.29.3'
overrides:
  sass-embedded: 1.100.0

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
minimumReleaseAge: 0
trustLockfile: true
