packages:
  - "packages/*"
packageExtensions:
  recast@0.23.11:
    dependencies:
      "@babel/parser": "7.29.3"
overrides:
  sass-embedded: 1.100.0

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - "@quasar/app-vite@3.0.0-beta.29"
  - "@oxfmt/binding-android-arm-eabi@0.52.0"
  - "@oxfmt/binding-android-arm64@0.52.0"
  - "@oxfmt/binding-darwin-arm64@0.52.0"
  - "@oxfmt/binding-darwin-x64@0.52.0"
  - "@oxfmt/binding-freebsd-x64@0.52.0"
  - "@oxfmt/binding-linux-arm-gnueabihf@0.52.0"
  - "@oxfmt/binding-linux-arm-musleabihf@0.52.0"
  - "@oxfmt/binding-linux-arm64-gnu@0.52.0"
  - "@oxfmt/binding-linux-arm64-musl@0.52.0"
  - "@oxfmt/binding-linux-ppc64-gnu@0.52.0"
  - "@oxfmt/binding-linux-riscv64-gnu@0.52.0"
  - "@oxfmt/binding-linux-riscv64-musl@0.52.0"
  - "@oxfmt/binding-linux-s390x-gnu@0.52.0"
  - "@oxfmt/binding-linux-x64-gnu@0.52.0"
  - "@oxfmt/binding-linux-x64-musl@0.52.0"
  - "@oxfmt/binding-openharmony-arm64@0.52.0"
  - "@oxfmt/binding-win32-arm64-msvc@0.52.0"
  - "@oxfmt/binding-win32-ia32-msvc@0.52.0"
  - "@oxfmt/binding-win32-x64-msvc@0.52.0"
  - "@oxlint/binding-android-arm-eabi@1.67.0"
  - "@oxlint/binding-android-arm64@1.67.0"
  - "@oxlint/binding-darwin-arm64@1.67.0"
  - "@oxlint/binding-darwin-x64@1.67.0"
  - "@oxlint/binding-freebsd-x64@1.67.0"
  - "@oxlint/binding-linux-arm-gnueabihf@1.67.0"
  - "@oxlint/binding-linux-arm-musleabihf@1.67.0"
  - "@oxlint/binding-linux-arm64-gnu@1.67.0"
  - "@oxlint/binding-linux-arm64-musl@1.67.0"
  - "@oxlint/binding-linux-ppc64-gnu@1.67.0"
  - "@oxlint/binding-linux-riscv64-gnu@1.67.0"
  - "@oxlint/binding-linux-riscv64-musl@1.67.0"
  - "@oxlint/binding-linux-s390x-gnu@1.67.0"
  - "@oxlint/binding-linux-x64-gnu@1.67.0"
  - "@oxlint/binding-linux-x64-musl@1.67.0"
  - "@oxlint/binding-openharmony-arm64@1.67.0"
  - "@oxlint/binding-win32-arm64-msvc@1.67.0"
  - "@oxlint/binding-win32-ia32-msvc@1.67.0"
  - "@oxlint/binding-win32-x64-msvc@1.67.0"
  - "@quasar/art@1.0.0"
  - oxfmt@0.52.0
  - oxlint@1.67.0
  - "@md-plugins/md-plugin-blockquote@0.1.0-beta.9"
  - "@md-plugins/md-plugin-codeblocks@0.1.0-beta.9"
  - "@md-plugins/md-plugin-containers@0.1.0-beta.9"
  - "@md-plugins/md-plugin-frontmatter@0.1.0-beta.9"
  - "@md-plugins/md-plugin-headers@0.1.0-beta.9"
  - "@md-plugins/md-plugin-image@0.1.0-beta.9"
  - "@md-plugins/md-plugin-imports@0.1.0-beta.9"
  - "@md-plugins/md-plugin-inlinecode@0.1.0-beta.9"
  - "@md-plugins/md-plugin-link@0.1.0-beta.9"
  - "@md-plugins/md-plugin-table@0.1.0-beta.9"
  - "@md-plugins/md-plugin-title@0.1.0-beta.9"
  - "@md-plugins/quasar-app-extension-q-press@0.1.0-beta.9"
  - "@md-plugins/shared@0.1.0-beta.9"
  - "@md-plugins/vite-examples-plugin@0.1.0-beta.9"
  - "@md-plugins/vite-md-plugin@0.1.0-beta.9"
